export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR"

export const GET_CART_PRODUCTS_REQUEST = "GET_CART_PRODUCTS_REQUEST"
export const GET_CART_PRODUCTS_SUCCESS = "GET_CART_PRODUCTS_SUCCESS"
export const GET_CART_PRODUCTS_ERROR = "GET_CART_PRODUCTS_ERROR"

export const DELETE_CART_PRODUCT_REQUEST = "DELETE_CART_PRODUCT_REQUEST"
export const DELETE_CART_PRODUCT_SUCCESS = "DELETE_CART_PRODUCT_SUCCESS"
export const DELETE_CART_PRODUCT_ERROR = "DELETE_CART_PRODUCT_ERROR"

export const INCREASE_CART_QUANTITY_REQUEST = "INCREASE_CART_QUANTITY_REQUEST"
export const INCREASE_CART_QUANTITY_SUCCESS = "INCREASE_CART_QUANTITY_SUCCESS"
export const INCREASE_CART_QUANTITY_ERROR = "INCREASE_CART_QUANTITY_ERROR"

export const DECREASE_CART_QUANTITY_REQUEST = "DECREASE_CART_QUANTITY_REQUEST"
export const DECREASE_CART_QUANTITY_SUCCESS = "DECREASE_CART_QUANTITY_SUCCESS"
export const DECREASE_CART_QUANTITY_ERROR = "DECREASE_CART_QUANTITY_ERROR"

export const ORDER_POST_REQUEST = "ORDER_POST_REQUEST";
export const ORDER_POST_SUCCESS = "ORDER_POST_SUCCESS";
export const ORDER_POST_ERROR = "ORDER_POST_ERROR";

export const ORDERS_GET_REQUEST = "ORDERS_GET_REQUEST";
export const ORDERS_GET_SUCCESS = "ORDERS_GET_SUCCESS";
export const ORDERS_GET_ERROR = "ORDERS_GET_ERROR";


