export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR"

export const GET_ALL_PRODUCTS_REQUEST = "GET_ALL_PRODUCTS_REQUEST"
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS"
export const GET_ALL_PRODUCTS_ERROR = "GET_ALL_PRODUCTS_ERROR"

export const SINGLE_PRODUCTS_REQUEST = "SINGLE_PRODUCTS_REQUEST";
export const SINGLE_PRODUCTS_SUCCESS = "SINGLE_PRODUCTS_SUCCESS";
export const SINGLE_PRODUCTS_ERROR = "SINGLE_PRODUCTS_ERROR";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR"

export const POST_PRODUCT_REQUEST = "POST_PRODUCT_REQUEST"
export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS"
export const POST_PRODUCT_ERROR = "POST_PRODUCT_ERROR"

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST"
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR"

export const SINGLE_PRODUCT_REQUEST = "SINGLE_PRODUCT_REQUEST";
export const SINGLE_PRODUCT_SUCCESS = "SINGLE_PRODUCT_SUCCESS";
export const SINGLE_PRODUCT_ERROR = "SINGLE_PRODUCT_ERROR";

export const SEARCH_QUERY_REQUEST = "SEARCH_QUERY_REQUEST";
export const SEARCH_QUERY_SUCCESS = "SEARCH_QUERY_SUCCESS";
export const SEARCH_QUERY_ERROR = "SEARCH_QUERY_ERROR";